Hospital/Hospital/Models/Especialidad.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Hospital.Models
{
    public partial class Especialidad
    {
        public Especialidad()
        {
            Doctors = new HashSet<Doctor>();
        }

        public int Iidespecialidad { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}

Hospital/Hospital/Controllers/EspecialidadController.cs
using Hospital.Clases;
using Hospital.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Controllers
{
    public class EspecialidadController : Controller
    {
        public IActionResult Index(EspecialidadCLS objEspecialidadCLS)
        {
            List<EspecialidadCLS> listEspecialidad = new List<EspecialidadCLS>();
            using (BDHospitalContext db= new BDHospitalContext())
            {
                if(objEspecialidadCLS.nombre == null || objEspecialidadCLS.nombre== "") {
                listEspecialidad = (from especialidad in db.Especialidads
                                    where especialidad.Bhabilitado == 1
                                    select new EspecialidadCLS
                                    {
                                        idEspecialidad = especialidad.Iidespecialidad,
                                        nombre = especialidad.Nombre,
                                        descripcion = especialidad.Descripcion
                                    }).ToList();
                    ViewBag.nombreEspecialidad = "";
                }
                else
                {
                    listEspecialidad = (from especialidad in db.Especialidads
                                        where especialidad.Bhabilitado == 1
                                        && especialidad.Nombre.Contains(objEspecialidadCLS.nombre)
                                        select new EspecialidadCLS
                                        {
                                            idEspecialidad = especialidad.Iidespecialidad,
                                            nombre = especialidad.Nombre,
                                            descripcion = especialidad.Descripcion
                                        }).ToList();
                    ViewBag.nombreEspecialidad = objEspecialidadCLS.nombre;
                }               
            }
            return View(listEspecialidad);
        }

        public IActionResult Agregar()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Agregar(EspecialidadCLS objEspecialidadCLS)
        {
            try 
            {
                using (BDHospitalContext db = new())
                {
                    if (!ModelState.IsValid)
                    {
                        return View(objEspecialidadCLS);
                    }
                    else 
                    {
                        Especialidad objEspecialidad = new Especialidad();
                        objEspecialidad.Nombre = objEspecialidadCLS.nombre;
                        objEspecialidad.Descripcion = objEspecialidadCLS.descripcion;
                        objEspecialidad.Bhabilitado = 1;
                        db.Especialidads.Add(objEspecialidad);
                        db.SaveChanges();
                    }
            }
            }
            catch
            {
                return View(objEspecialidadCLS);
            }
         

                return RedirectToAction("Index");
        }

    }
}

Hospital/Hospital/Views/Especialidad/Agregar.cshtml
@using Hospital.Clases
@model EspecialidadCLS
@{
    ViewData["Title"] = "Agregar";
}

<div class="row">
    <div class="col-md-6">
        <form asp-controller="Especialidad" asp-action="Agregar" method="post" id="frmEnviar">
            <div class=" form-group">
                <label asp-for="nombre"></label>
                <input asp-for="nombre" class="form-check form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class=" form-group">
                <label asp-for="descripcion"></label>
                <input asp-for="descripcion" class="form-check form-control" />
                <span asp-validation-for="descripcion" class="text-danger"></span>
            </div>
            <div class=" form-group">
                <input value="Agregar" type="button" class="btn btn-primary" onclick="ModalConfirmacion()"/>
                <a asp-controller="Especialidad" asp-action="Index" class="btn btn-danger">Regresar</a>
            </div>
        </form>
    </div>
</div>


<script src="~/js/sweetalert.js"></script>
<script src="~/js/generico.js"></script>
<script>
    function ModalConfirmacion()
    {
        modalGuargar().then((result) =>
        {
            if (result.isConfirmed)
            {            
                 var frmEnviar = document.getElementById("frmEnviar").submit();              
            }
        })
    }
</script>

Hospital/Hospital/Views/Especialidad/Index.cshtml
@using Hospital.Clases;
@model IEnumerable<EspecialidadCLS>
@{ 
    string nombreEspecialidad = ViewBag.nombreEspecialidad;
}
<a class= "btn btn-primary"  asp-controller="Especialidad" asp-action="Agregar">Agregar</a>
<form asp-controller="Especialidad" asp-action="Index" method="post" class="mb-2" style="display:grid; grid-template-columns: 1fr 2fr 1fr 1fr" id="frmFormulario">
    <label>Ingrese nombre Especialidad</label>
    <input type="text" class="form-check form-control" name="nombre" value="@nombreEspecialidad" id="nombre" />
    <input type="submit" value="Buscar" class="btn btn-info" />
    <input type="button" value="Limpiar" class="btn btn-danger" onclick="Limpiar()" />
</form>
<table class="table">   
    <thead class=" thead-dark">
        <tr>
            <th>@Html.DisplayNameFor(model => model.idEspecialidad) </th>
            <th>@Html.DisplayNameFor(model => model.nombre)</th>
            <th>@Html.DisplayNameFor(model => model.descripcion)</th>
        </tr>
    </thead>
    <tbody>
        @foreach (EspecialidadCLS objEspecialidadCLS in Model)
        {
            <tr>
                <td>@objEspecialidadCLS.idEspecialidad</td>
                <td>@objEspecialidadCLS.nombre</td>
                <td>@objEspecialidadCLS.descripcion</td>
                <td>
                    <button class="btn btn-outline-danger"  onclick="Eliminar(@objEspecialidadCLS.idEspecialidad)">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
                            <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"></path>
                            <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"></path>
                        </svg>
                    </button>
                    
                </td>
            </tr>
        }

    </tbody>
</table>
<script>
    function Limpiar() {
        document.getElementById("nombre").value = "";
        document.getElementById("frmFormulario").submit();
    }
    function Eliminar(idEspecialidad) {
        alert(idEspecialidad)
    }
</script>