Hospital/Hospital/Models/Medicamento.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Hospital.Models
{
    public partial class Medicamento
    {
        public Medicamento()
        {
            CitaMedicamentos = new HashSet<CitaMedicamento>();
        }

        public int Iidmedicamento { get; set; }
        public string Nombre { get; set; }
        public string Concentracion { get; set; }
        public int? Iidformafarmaceutica { get; set; }
        public decimal? Precio { get; set; }
        public int? Stock { get; set; }
        public string Presentacion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual FormaFarmaceutica IidformafarmaceuticaNavigation { get; set; }
        public virtual ICollection<CitaMedicamento> CitaMedicamentos { get; set; }
    }
}

Hospital/Hospital/Controllers/MedicamentoController.cs
using Hospital.Clases;
using Hospital.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Controllers
{
    public class MedicamentoController : Controller
    {
        public List<SelectListItem> LlenarFormaFarmaceutica()
        {
            List<SelectListItem> listaFormaFarmaceutica = new();
            using (BDHospitalContext db = new BDHospitalContext())
            {
                listaFormaFarmaceutica = (from formaFarmaceutica in db.FormaFarmaceuticas
                                          where formaFarmaceutica.Bhabilitado == 1
                                          select new SelectListItem
                                          {
                                              Text = formaFarmaceutica.Nombre,
                                              Value = formaFarmaceutica.Iidformafarmaceutica.ToString()
                                          }).ToList();
                listaFormaFarmaceutica.Insert(0, new SelectListItem
                {
                    Text = "--Todos--",
                    Value = ""
                }
                );
            }
            return listaFormaFarmaceutica;
        }

        public IActionResult Index(MedicamentosCLS objMedicamentosCLS)
        {
            ViewBag.listaFormaFarmaceutica = LlenarFormaFarmaceutica();
            List<MedicamentosCLS> listMedicamentoCls = new();
            using (BDHospitalContext db = new())
            {
                if (objMedicamentosCLS.iidFormaFarmaceutica == null || objMedicamentosCLS.iidFormaFarmaceutica == 0)
                {
                    listMedicamentoCls = (from medicamento in db.Medicamentos
                                          join formaFarmaceutica in db.FormaFarmaceuticas
                                          on medicamento.Iidformafarmaceutica equals formaFarmaceutica.Iidformafarmaceutica
                                          where medicamento.Bhabilitado == 1
                                          select new MedicamentosCLS
                                          {
                                              idMedicamento = medicamento.Iidmedicamento,
                                              nombreMedicamento = medicamento.Nombre,
                                              concentracionMedicamento = medicamento.Concentracion,
                                              formaFamaceutica = formaFarmaceutica.Nombre,
                                              precio = (decimal)medicamento.Precio,
                                              stock = (int)medicamento.Stock,
                                              presentacion = medicamento.Presentacion
                                          }).ToList();
                }
                else
                {
                    listMedicamentoCls = (from medicamento in db.Medicamentos
                                          join formaFarmaceutica in db.FormaFarmaceuticas
                                          on medicamento.Iidformafarmaceutica equals formaFarmaceutica.Iidformafarmaceutica
                                          where medicamento.Bhabilitado == 1
                                          && medicamento.Iidformafarmaceutica == objMedicamentosCLS.iidFormaFarmaceutica
                                          select new MedicamentosCLS
                                          {
                                              idMedicamento = medicamento.Iidmedicamento,
                                              nombreMedicamento = medicamento.Nombre,
                                              concentracionMedicamento = medicamento.Concentracion,
                                              formaFamaceutica = formaFarmaceutica.Nombre,
                                              precio = (decimal)medicamento.Precio,
                                              stock = (int)medicamento.Stock,
                                              presentacion = medicamento.Presentacion
                                          }).ToList();
                }

            }
            return View(listMedicamentoCls);
        }
        public IActionResult Agregar()
        {
            ViewBag.listaFormaFarmaceutica = LlenarFormaFarmaceutica();

            return View();
        }
        [HttpPost]
        public IActionResult Agregar(MedicamentosCLS objMedicamentoCLS)
        {
            try
            {
                using (BDHospitalContext db = new())
                {
                    if (!ModelState.IsValid)
                    {
                        ViewBag.listaFormaFarmaceutica = LlenarFormaFarmaceutica();
                        return View(objMedicamentoCLS);

                    }
                    else
                    {
                        Medicamento objMedicamento = new Medicamento();
                        objMedicamento.Nombre = objMedicamentoCLS.nombreMedicamento;
                        objMedicamento.Precio = objMedicamentoCLS.precio;
                        objMedicamento.Presentacion = objMedicamentoCLS.presentacion;
                        objMedicamento.Stock = objMedicamentoCLS.stock;
                        objMedicamento.Iidformafarmaceutica = objMedicamentoCLS.iidFormaFarmaceutica;
                        objMedicamento.Concentracion = objMedicamentoCLS.concentracionMedicamento;
                        objMedicamento.Bhabilitado = 1;
                        db.Medicamentos.Add(objMedicamento);
                        db.SaveChanges();                       
                    }
                }
            }
            catch (Exception ex)
            {
                ViewBag.listaFormaFarmaceutica = LlenarFormaFarmaceutica();
                return View(objMedicamentoCLS);

            }

            return RedirectToAction("Index");
        }
    }
}

Hospital/Hospital/Views/Medicamento/Agregar.cshtml
@using Hospital.Clases
@model MedicamentosCLS
@{
    ViewData["Title"] = "Agregar";
    List<SelectListItem> listaFormaFarmaceutica = ViewBag.listaFormaFarmaceutica;
}

<h1>Formulario Agregar Medicamento</h1>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Agregar" asp-controller="Medicamento" method="post" id="frmEnviar">
            <div class="form-group">
                <label asp-for="nombreMedicamento"></label>
                <input type="text" class="form form-control" asp-for="nombreMedicamento" />
                <span asp-validation-for="nombreMedicamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="concentracionMedicamento"></label>
                <input type="text" class="form form-control" asp-for="concentracionMedicamento " />
                <span asp-validation-for="concentracionMedicamento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="iidFormaFarmaceutica"></label>
                <select asp-for="iidFormaFarmaceutica" class="form form-control" asp-items="@listaFormaFarmaceutica"></select>
                <span asp-validation-for="iidFormaFarmaceutica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="precio"></label>
                <input type="text" class="form form-control" asp-for="precio " />
                <span asp-validation-for="precio" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="stock"></label>
                <input type="number" class="form form-control" asp-for="stock " />
                <span asp-validation-for="stock" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="presentacion"></label>
                <input type="text" class="form form-control" asp-for="presentacion " />
                <span asp-validation-for="presentacion" class="text-danger"></span>
            </div>
            <div class=" form-group">
                <input value="Agregar" type="button" class="btn btn-primary" onclick="ModalConfirmacion()" />
                <a asp-controller="Medicamento" asp-action="Index" class="btn btn-danger">Regresar</a>
            </div>
        </form>
    </div>
</div>
<script src="~/js/sweetalert.js"></script>
<script src="~/js/generico.js"></script>
<script>
    function ModalConfirmacion() {
        modalGuargar().then((result) => {
            if (result.isConfirmed) {
                var frmEnviar = document.getElementById("frmEnviar");
                frmEnviar.submit();
            }
        })
    }
</script>

Hospital/Hospital/Views/Medicamento/Index.cshtml
@model IEnumerable<Hospital.Clases.MedicamentosCLS>

@{
    ViewData["Title"] = "Index";
    List<SelectListItem> listaFormaFarmaceutica = ViewBag.listaFormaFarmaceutica;
}

<a class="btn btn-primary" asp-controller="Medicamento" asp-action="Agregar">Agregar</a>
<form asp-controller="Medicamento" asp-action="Index" style="display: grid; grid-template-columns: 1fr 2fr" class="mb-2" id="frmFormaFarmaceutica">
    <label>Ingrese nombre de la forma farmacéutica</label>
    @Html.DropDownList("iidFormaFarmaceutica", listaFormaFarmaceutica, new { @class = "form form-control" })
</form>


<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idMedicamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombreMedicamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.concentracionMedicamento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.formaFamaceutica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.precio)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.stock)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.presentacion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idMedicamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombreMedicamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.concentracionMedicamento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.formaFamaceutica)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.precio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.stock)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.presentacion)
            </td>
        
        </tr>
}
    </tbody>
</table>
<script>
    var iidFormaFarmaceutia = document.getElementById("iidFormaFarmaceutica");
    iidFormaFarmaceutia.onchange = function () {

        document.getElementById("frmFormaFarmaceutica").submit();
    }
</script>