Hospital/Hospital/Models/Sede.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Hospital.Models
{
    public partial class Sede
    {
        public Sede()
        {
            Cita = new HashSet<Citum>();
            Doctors = new HashSet<Doctor>();
        }

        public int Iidsede { get; set; }
        public string Nombre { get; set; }
        public string Direccion { get; set; }
        public int? Bhabilitado { get; set; }

        public virtual ICollection<Citum> Cita { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
    }
}

Hospital/Hospital/Controllers/SedeController.cs
using Hospital.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Controllers
{
    public class SedeController : Controller
    {
        public IActionResult Index(SedeCLS objSedeCLS)
        {
            List<SedeCLS> listSedeCLS = new();
            using (BDHospitalContext db = new())
            {
                if(objSedeCLS.nombre == "" ||objSedeCLS.nombre == null)
                {
                    listSedeCLS = (from sede in db.Sedes
                                   where sede.Bhabilitado == 1
                                   select new SedeCLS
                                   {
                                       idSede = sede.Iidsede,
                                       nombre = sede.Nombre,
                                       direccion = sede.Direccion

                                   }).ToList();
                    ViewBag.nombreSedeCLS = "";
                }
                else 
                {
                    listSedeCLS = (from sede in db.Sedes
                                   where sede.Bhabilitado == 1
                                   && sede.Nombre.Contains(objSedeCLS.nombre)
                                   select new SedeCLS
                                   {
                                       idSede = sede.Iidsede,
                                       nombre = sede.Nombre,
                                       direccion = sede.Direccion
                                   }).ToList();
                    ViewBag.nombreSedeCLS = objSedeCLS.nombre;                }

            }
                return View(listSedeCLS);
        }
    }
}

Hospital/Hospital/Views/Sede/Index.cshtml
@model IEnumerable<Hospital.Controllers.SedeCLS>
@{ 
    string nombreSedeCLS = ViewBag.nombreSedeCLS;

}

<form asp-controller="Sede" asp-action="Index" method="post" id="frmFormulario" class="mb-2" style="display:grid; grid-template-columns: 1fr 2fr">
    <label>Ingrese nombre Sede:</label>
    <input type="text" name="nombre"  value="@nombreSedeCLS" id="nombreSede" onkeyup="Buscar()"/>
</form>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.idSede)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.nombre)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.direccion)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idSede)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.nombre)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.direccion)
            </td>
            <td>
            </td>
        </tr>
}
    </tbody>
</table>
<script>
    function Buscar() {
        document.getElementById("frmFormulario").submit();
    }
</script>