Hospital/Hospital/Models/Persona.cs
using System;
using System.Collections.Generic;

#nullable disable

namespace Hospital.Models
{
    public partial class Persona
    {
        public Persona()
        {
            Cita = new HashSet<Citum>();
            Doctors = new HashSet<Doctor>();
            Usuarios = new HashSet<Usuario>();
        }

        public int Iidpersona { get; set; }
        public string Nombre { get; set; }
        public string Appaterno { get; set; }
        public string Apmaterno { get; set; }
        public string Email { get; set; }
        public string Direccion { get; set; }
        public string Telefonofijo { get; set; }
        public string Telefonocelular { get; set; }
        public DateTime? Fechanacimiento { get; set; }
        public int? Iidsexo { get; set; }
        public int? Bdoctor { get; set; }
        public int? Bpaciente { get; set; }
        public int? Bhabilitado { get; set; }
        public string Foto { get; set; }
        public int? Btieneusuario { get; set; }
        public int? Iidusuario { get; set; }

        public virtual Sexo IidsexoNavigation { get; set; }
        public virtual Usuario IidusuarioNavigation { get; set; }
        public virtual ICollection<Citum> Cita { get; set; }
        public virtual ICollection<Doctor> Doctors { get; set; }
        public virtual ICollection<Usuario> Usuarios { get; set; }
    }
}

Hospital/Hospital/Controllers/PersonaController.cs
using Hospital.Clases;
using Hospital.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Hospital.Controllers
{
    public class PersonaController : Controller
    {
        public void LlenarSexo()
        {
            List<SelectListItem> listaSexo = new();
            using (BDHospitalContext db = new BDHospitalContext())
            {
                listaSexo = (from sexo in db.Sexos
                             where sexo.Bhabilitado == 1
                             select new SelectListItem
                             {
                                 Value = sexo.Iidsexo.ToString(),
                                 Text = sexo.Nombre
                             }).ToList();
                listaSexo.Insert(0, new SelectListItem
                {
                    Value = "",
                    Text = "--Inserte sexo "

                });
            }
            ViewBag.listaSexo = listaSexo;
        }
        public IActionResult Index(PersonaCLS objPersonaCLS)
        {
            List<PersonaCLS> listPersonaCLS = new List<PersonaCLS>();
            LlenarSexo();
            using (BDHospitalContext db = new BDHospitalContext())
            {
                if (objPersonaCLS.iidSexo == null ||objPersonaCLS.iidSexo == 0)
                {
                    listPersonaCLS = (from persona in db.Personas
                                      join sexo in db.Sexos
                                      on persona.Iidsexo equals sexo.Iidsexo
                                      where persona.Bhabilitado == 1
                                      select new PersonaCLS
                                      {
                                          idPersonas = persona.Iidpersona,
                                          nombreCompleto = persona.Nombre + " " + persona.Appaterno + " " + persona.Apmaterno,
                                          email = persona.Email,
                                          sexo = sexo.Nombre

                                      }).ToList();
                }
                else
                {

                    listPersonaCLS = (from persona in db.Personas
                                      join sexo in db.Sexos
                                      on persona.Iidsexo equals sexo.Iidsexo
                                      where persona.Bhabilitado == 1
                                      && persona.Iidsexo == objPersonaCLS.iidSexo
                                      select new PersonaCLS
                                      {
                                          idPersonas = persona.Iidpersona,
                                          nombreCompleto = persona.Nombre + " " + persona.Appaterno + " " + persona.Apmaterno,
                                          email = persona.Email,
                                          sexo = sexo.Nombre

                                      }).ToList();


                }
            }
            return View(listPersonaCLS);
        }

        public IActionResult Agregar()
        {
            LlenarSexo();
            return View();
        }

        [HttpPost]
        public IActionResult Agregar(PersonaCLS objPersonaCLS)
        {
            LlenarSexo();
            try
            {
                using (BDHospitalContext db = new BDHospitalContext())
                {
                    if (!ModelState.IsValid)
                    {
                        return View(objPersonaCLS);
                    }
                    else
                    {
                        Persona objPersona = new();
                        objPersona.Nombre = objPersonaCLS.nombre;
                        objPersona.Appaterno = objPersonaCLS.apPaterno;
                        objPersona.Apmaterno = objPersonaCLS.apMaterno;
                        objPersona.Telefonofijo = objPersonaCLS.telefonoFijo;
                        objPersona.Telefonocelular = objPersonaCLS.telefonoCelular;
                        objPersona.Fechanacimiento = objPersonaCLS.fechaNacimiento;
                        objPersona.Email = objPersonaCLS.email;
                        objPersona.Iidsexo = objPersonaCLS.iidSexo;
                        objPersona.Bhabilitado = 1;
                        db.Personas.Add(objPersona);
                        db.SaveChanges();
                    }
                }
            }
            catch (Exception ex)
            {
                return View(objPersonaCLS);
            }

            return RedirectToAction("Index");
        }
    }
}

Hospital/Hospital/Views/Persona/Agregar.cshtml
@model Hospital.Clases.PersonaCLS

@{
    ViewData["Title"] = "Agregar";
    List<SelectListItem> listaSexo = ViewBag.listaSexo;
}

<h1>Agregar Persona</h1>

<h4>PersonaCLS</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="Agregar" asp-controller="Persona" method="post" id="frmEnviar">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
      
            <div class="form-group">
                <label asp-for="nombre" class="control-label"></label>
                <input asp-for="nombre" class="form-control" />
                <span asp-validation-for="nombre" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apPaterno" class="control-label"></label>
                <input asp-for="apPaterno" class="form-control" />
                <span asp-validation-for="apPaterno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="apMaterno" class="control-label"></label>
                <input asp-for="apMaterno" class="form-control" />
                <span asp-validation-for="apMaterno" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefonoFijo" class="control-label"></label>
                <input asp-for="telefonoFijo" class="form-control" />
                <span asp-validation-for="telefonoFijo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefonoCelular" class="control-label"></label>
                <input asp-for="telefonoCelular" class="form-control" />
                <span asp-validation-for="telefonoCelular" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="fechaNacimiento" class="control-label"></label>
                <input asp-for="fechaNacimiento" class="form-control" />
                <span asp-validation-for="fechaNacimiento" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="email" class="control-label"></label>
                <input asp-for="email" class="form-control" />
                <span asp-validation-for="email" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="iidSexo" class="control-label"></label>
                <select asp-for="iidSexo" class="form-control" asp-items="@listaSexo"></select>
                <span asp-validation-for="iidSexo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="button" class="btn btn-primary" value="Agregar" onclick="ModalConfirmacion()"/>
                <a class="btn btn-danger" asp-controller="Persona" asp-action="Index">Regresar</a>
            </div>
        </form>
    </div>
</div>
<script src="~/js/sweetalert.js"></script>
<script src="~/js/generico.js"></script>

<script>
    function ModalConfirmacion() {
        modalGuargar().then((result) => {
            if (result.isConfirmed) {
                var frmEnviar = document.getElementById("frmEnviar");
                frmEnviar.submit();
            }
        })
    }
</script>

Hospital/Hospital/Views/Persona/Index.cshtml
@using Hospital.Clases;
@model IEnumerable<PersonaCLS>;
@{
    List<SelectListItem> listaSexo = ViewBag.listaSexo;
 }
<a class="btn btn-primary" asp-action="Agregar" asp-controller="Persona" >Agregar</a>
<form asp-controller="Persona" asp-action="Index" id="frmFiltroSexo" method="post" class="mb-2" style=" display:grid; grid-template-columns: 1fr 2fr 1fr 1fr">
    <label>Inserte Sexo</label>
    @Html.DropDownList("iidSexo", listaSexo, new { @class ="form form-control" })
    <input type="submit" value="Buscar" class="btn btn-info"/>
    <input type ="button" value="Limpiar" class=" btn btn-danger" onclick="Limpiar()"/>
</form>
    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>@Html.DisplayNameFor(model => model.idPersonas)</th>
                <th>@Html.DisplayNameFor(model => model.nombreCompleto)</th>
                <th>@Html.DisplayNameFor(model => model.email)</th>
                <th>@Html.DisplayNameFor(model => model.sexo)</th>
            </tr>
        </thead>
        <tbody>
            @foreach (PersonaCLS objPersonaCLS in Model)
            {
                <tr>
                    <td>@objPersonaCLS.idPersonas</td>
                    <td>@objPersonaCLS.nombreCompleto</td>
                    <td>@objPersonaCLS.email</td>
                    <td>@objPersonaCLS.sexo</td>
                </tr>
            }

        </tbody>
    </table>
<script>
    function Limpiar() {
        document.getElementById("iidSexo").value = "";
        document.getElementById("frmFiltroSexo").submit();
    }
</script>